// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_8nh4cs_o5HI7IuH1d82foqrq8pebKI',
    appId: '1:868475064396:web:6cc51e7bf3b1753fd1e4e9',
    messagingSenderId: '868475064396',
    projectId: 'ai-chat5180976',
    authDomain: 'ai-chat5180976.firebaseapp.com',
    storageBucket: 'ai-chat5180976.firebasestorage.app',
    measurementId: 'G-RVM7JF6W7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm712KhovjDnjpWKLMBUxUh4F-KTS4xng',
    appId: '1:868475064396:android:151337368a581e45d1e4e9',
    messagingSenderId: '868475064396',
    projectId: 'ai-chat5180976',
    storageBucket: 'ai-chat5180976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTe_GpBrsSVVYYSJ3PIsGsCyPUQP-3PU',
    appId: '1:868475064396:ios:3bb4da527bda450ad1e4e9',
    messagingSenderId: '868475064396',
    projectId: 'ai-chat5180976',
    storageBucket: 'ai-chat5180976.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTe_GpBrsSVVYYSJ3PIsGsCyPUQP-3PU',
    appId: '1:868475064396:ios:3bb4da527bda450ad1e4e9',
    messagingSenderId: '868475064396',
    projectId: 'ai-chat5180976',
    storageBucket: 'ai-chat5180976.firebasestorage.app',
    iosBundleId: 'com.example.aiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs_8nh4cs_o5HI7IuH1d82foqrq8pebKI',
    appId: '1:868475064396:web:bf258ab12af4992cd1e4e9',
    messagingSenderId: '868475064396',
    projectId: 'ai-chat5180976',
    authDomain: 'ai-chat5180976.firebaseapp.com',
    storageBucket: 'ai-chat5180976.firebasestorage.app',
    measurementId: 'G-6Z7V26Y0HW',
  );
}
